## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /nas/asallard/Ile-de-France/cache

# This section defines which parts of the pipeline should be run
run:
  #- data.bdtopo.raw
  #- synthesis.output # To create the output population in the output_path (see below)
  #- matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)
  - jtab_preparation.population_clustering
  - jtab_preparation.prepare_jtab_outputs

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 4

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: entd_long_distances

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.001
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: /nas/asallard/Ile-de-France/Data
  output_path: /nas/asallard/Ile-de-France/output
  jtab_data_path: /nas/asallard/Ile-de-France/JTAB_data
  jtab_output_path: /nas/asallard/Ile-de-France/JTAB_output

  # Only interesting if you run the simulation
  java_memory: 14G

  # Uncommented below to enable vehicle fleet generation
  # generate_vehicles_file: True
  # generate_vehicles_method: fleet_sample
  # vehicles_data_year: 2015
