name: Unit and integration tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install conda dependencies
      run: |
        conda env update --file environment.yml --name base

    # This comes with Maven
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Install Osmosis
      run: |
        wget https://github.com/openstreetmap/osmosis/releases/download/0.48.2/osmosis-0.48.2.tgz -O osmosis.tgz
        tar xf osmosis.tgz -C $HOME/osmosis
        echo $HOME/osmosis >> $GITHUB_PATH

    - name: Test versions
      run: |
        java -v
        mvn -v
        python3 --version
        osmosis -v
        git --version

    - name: Run pipeline tests
      run: |
        MKL_CBWR=AUTO pytest tests/
